name: Build macOS Executable

on:
  push:
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: read
    env:
      EXPECTED_DESCRIPTION: "Rutoken Wallet PKCS #11 library"
      PKCS11_VERSION: "3rdparty"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install native dependencies
        run: |
          brew update
          brew install pcsc-lite || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: 'requirements-build.txt'

      - name: Install build dependencies
        run: pip install -r requirements-build.txt

      - name: Cache WT PKCS#11 files
        id: cache-pkcs11
        uses: actions/cache@v4
        with:
          path: |
            .cache/wtpkcs11ecp
            libwtpkcs11ecp.dylib
          key: pkcs11-${{ runner.os }}-${{ env.PKCS11_VERSION }}

      - name: Download WT PKCS#11 .dylib
        if: steps.cache-pkcs11.outputs.cache-hit != 'true'
        run: |
          python scripts/download_wtpkcs11ecp.py \
            --tag 3rdparty \
            --pattern macos \
            --pattern x86_64 \
            --library-pattern libwtpkcs11ecp.dylib

      - name: Build executable
        run: pyinstaller --onefile main.py

      - name: Copy .dylib
        run: cp libwtpkcs11ecp.dylib dist/

      - name: Test application
        run: |
          output=$(./dist/main --library-info 2>&1)
          echo "App output:"
          echo "$output"

          if ! echo "$output" | grep -F "Library Description: $EXPECTED_DESCRIPTION"; then
            echo "❌ Не удалось найти ожидаемую строку 'Library Description: $EXPECTED_DESCRIPTION'" >&2
            exit 1
          fi
          echo "✅ Библиотека загружена"

      - name: Upload macOS package
        uses: actions/upload-artifact@v4
        with:
          name: macos-package
          path: dist/**
