# .github/workflows/build-linux.yml
name: Build Linux Executable
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
      options: --user root
    env:
      EXPECTED_DESCRIPTION: "Rutoken ECP PKCS #11 library"

    steps:
      - uses: actions/checkout@v4

      - name: Install native dependencies
        run: sudo apt-get update && sudo apt-get install -y libpcsclite1 python3 python3-pip curl unzip

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Download RT PKCS#11 .so
        run: |
          curl -L -o librtpkcs11ecp.so \
            http://download.rutoken.ru/Rutoken/PKCS11Lib/Current/Linux/x64/librtpkcs11ecp.so

      - name: Install PyInstaller
        run: pip3 install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile main.py
        
      - name: copy .so
        run: cp librtpkcs11ecp.so dist/

      - name: Test application
        run: |
          # запускаем бинарь и захватываем оба потока
          output=$(./dist/main --library-info 2>&1)
          echo "App output:"
          echo "$output"

          # проверяем ожидаемую строку
          if ! echo "$output" | grep -F "Library Description: $EXPECTED_DESCRIPTION"; then
            echo "❌ Не удалось найти ожидаемую строку 'Library Description: $EXPECTED_DESCRIPTION'" >&2
            exit 1
          fi
          echo "✅ Библиотека загружена"

      - name: Upload Linux package
        uses: actions/upload-artifact@v4
        with:
          name: linux-package
          path: dist/**
