# .github/workflows/build-linux.yml
name: Build Linux Executable
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      EXPECTED_DESCRIPTION: "Rutoken Wallet PKCS #11 library"
      PKCS11_VERSION: "3rdparty" # bump to refresh cache when library updates
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install native dependencies
        run: sudo apt-get update && sudo apt-get install -y libpcsclite1 curl unzip

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: 'requirements-build.txt'

      - name: Install build dependencies
        run: pip install -r requirements-build.txt

      - name: Cache WT PKCS#11 files
        id: cache-pkcs11
        uses: actions/cache@v4
        with:
          path: |
            .cache/wtpkcs11ecp
            libwtpkcs11ecp.so
          key: pkcs11-${{ runner.os }}-${{ env.PKCS11_VERSION }}

      - name: Download WT PKCS#11 .so
        if: steps.cache-pkcs11.outputs.cache-hit != 'true'
        run: |
          python scripts/download_wtpkcs11ecp.py \
            --pattern linux \
            --pattern x86_64 \
            --library-pattern libwtpkcs11ecp.so

      - name: Build executable
        run: pyinstaller --onefile main.py
        
      - name: copy .so
        run: cp libwtpkcs11ecp.so dist/

      - name: Test application
        run: |
          # запускаем бинарь и захватываем оба потока
          output=$(./dist/main --library-info 2>&1)
          echo "App output:"
          echo "$output"

          # проверяем ожидаемую строку
          if ! echo "$output" | grep -F "Library Description: $EXPECTED_DESCRIPTION"; then
            echo "❌ Не удалось найти ожидаемую строку 'Library Description: $EXPECTED_DESCRIPTION'" >&2
            exit 1
          fi
          echo "✅ Библиотека загружена"

      - name: Upload Linux package
        uses: actions/upload-artifact@v4
        with:
          name: linux-package
          path: dist/**
